env:
  browser: true
  es2021: true
  node: true
  jest: true
extends: eslint:recommended
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaVersion: 2020
rules: 
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
